### ISSUE TITLE
Import error in Nuxt3.11.2

### ISSUE THREAD

**Issue by noah4520** [Rock070/vue3-noti#47]
### Describe the bug

When running `pnpm dev` to start the development server, the following error occurs:

```
[3:50:55 PM]  ERROR  Cannot start nuxt:  Template not found: /Users/chenxinyu/Documents/Github/test-noti/node_modules/.pnpm/@vue3-noti+nuxt@1.0.0-beta.3_@vueuse+core@10.9.0_vue@3.4.27/node_modules/@vue3-noti/nuxt/dist/options.d.ts

  at normalizeTemplate (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2775:13)
  at addTemplate (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2748:20)
  at setup (node_modules/.pnpm/@vue3-noti+nuxt@1.0.0-beta.3_@vueuse+core@10.9.0_vue@3.4.27/node_modules/@vue3-noti/nuxt/dist/module.mjs:15:5)
  at normalizedModule (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2112:37)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.11.2/node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.59.4_floating-vue@5.2.2_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/index.mjs:4233:7)
  at async NuxtDevServer._load (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/dev2.mjs:6879:5)
  at async NuxtDevServer.load (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/dev2.mjs:6811:7)
  at async NuxtDevServer.init (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/dev2.mjs:6806:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.11.1/node_modules/nuxi/dist/chunks/dev-child.mjs:99:5)
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qj7mbv?file=nuxt.config.ts

### Steps to reproduce

1. Create a new nuxt project，`npx nuxi@latest init <project-name>`.
2. Install vue3-lottie，`pnpm add -D @vue3-noti/nuxt`.
3. Add modules '@vue3-noti/nuxt' in `nuxt.config.ts`.
```typescript
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@vue3-noti/nuxt"]
})
```
4. Running `pnpm dev` to start the development server.
5. See error.

### dependencies
```
  "dependencies": {
    "nuxt": "^3.11.2",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "@vue3-noti/nuxt": "1.0.0-beta.3"
  }
```

**Comment by abe1272001** [comment]
Reproduced stackblitz cannot install dependencies.

![截圖 2024-05-07 16 23 43](https://github.com/Rock070/vue3-noti/assets/46858104/32c639fb-da42-4df8-86f6-08d7d3f7622a)

**Comment by noah4520** [comment]
In the Releases tags, I noticed version [1.0.0-beta.5](https://github.com/Rock070/vue3-noti/releases/tag/1.0.0-beta.5)

```
"devDependencies": {
  "@vue3-noti/nuxt": "1.0.0-beta.5"
}
```

but I encountered an issue while trying to install it:

```
> pnpm install

ERR_PNPM_WORKSPACE_PKG_NOT_FOUND: "@vue3-noti/core@workspace:*" is in the dependencies but no package named "@vue3-noti/core" is present in the workspace.

This error occurred while installing the dependencies of @vue3-noti/nuxt@1.0.0-beta.5.

Packages found in the workspace: 
Progress: resolved 1, reused 0, downloaded 0, added 0.

```

**Comment by Rock070** [comment]
The issue happened because I published the wrong npm version , please install newest version `v1.0.1`, I think would solve this
